### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by derrickbeining** [dylex/postgresql-typed#27]
This might be a dumb question: what's the recommended way to do connection pooling with `postgresql-typed`? Should I be able to use something like `resource-pool`? I saw this in the docs for `PGConnection` 

> These objects are not thread-safe and must only be used for a single request at a time.

And wasn't sure if that had any consequence for pooling connections.

**Comment by dylex** [comment]
Yes, you can certainly use resource-pool and we have in production. You just have to make sure any queries are complete before returning it to the pool.  This is not usually a problem unless you're using `pgLazyQuery` or low-level prepared query interface like `pgFetch`, in which case you just have to get all the results first.

I have sometimes worried about exceptions if something goes wrong, or the server shuts down or something, and providing a way to use `createPoolCheckAlive` but in practice have never had any issues with this, so haven't bothered.

**Comment by derrickbeining** [comment]
okay great! and thanks for the clarification

**Comment by avanov** [comment]
@derrickbeining @dylex do you happen to know if such a pool released anywhere as an open-source package?

**Comment by dylex** [comment]
Using it with `resource-pool` is almost too simple to need a package:
```
pool <- createPool (pgConnect ..) pgDisconnect 1 300 8
withResource pool $ \db -> ...
destroyAllResources pool
```

**Comment by avanov** [comment]
A proper pool will have to take care of various errors too, so that a connection gets removed from a pool when unrecoverable Client/Session/Server errors occur. That would be a nice pice of logic to reuse universally as a library. For instance, here is what considered unrecoverable in a Python [pool library](https://github.com/sqlalchemy/sqlalchemy/blob/1522d1935113ceb05a6e0c46dbaa8aff2d09ce8a/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L804). Haskell implementation could handle it with [postgresql-error-codes](https://hackage.haskell.org/package/postgresql-error-codes-1.0.1/docs/PostgreSQL-ErrorCodes.html).

**Comment by avanov** [comment]
Another thing that would fit a library purpose is various callbacks to observe/track pool statistics for monitoring purposes. They tend to repeat from project to project so that they are good candidates to be put together as a library component.
